// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: datasage.proto

package grpc_config

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataSageServerClient is the client API for DataSageServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataSageServerClient interface {
	LogSend(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Null, error)
}

type dataSageServerClient struct {
	cc grpc.ClientConnInterface
}

func NewDataSageServerClient(cc grpc.ClientConnInterface) DataSageServerClient {
	return &dataSageServerClient{cc}
}

func (c *dataSageServerClient) LogSend(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Null, error) {
	out := new(Null)
	err := c.cc.Invoke(ctx, "/DataSageServer/LogSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataSageServerServer is the server API for DataSageServer service.
// All implementations must embed UnimplementedDataSageServerServer
// for forward compatibility
type DataSageServerServer interface {
	LogSend(context.Context, *Log) (*Null, error)
	mustEmbedUnimplementedDataSageServerServer()
}

// UnimplementedDataSageServerServer must be embedded to have forward compatible implementations.
type UnimplementedDataSageServerServer struct {
}

func (UnimplementedDataSageServerServer) LogSend(context.Context, *Log) (*Null, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogSend not implemented")
}
func (UnimplementedDataSageServerServer) mustEmbedUnimplementedDataSageServerServer() {}

// UnsafeDataSageServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataSageServerServer will
// result in compilation errors.
type UnsafeDataSageServerServer interface {
	mustEmbedUnimplementedDataSageServerServer()
}

func RegisterDataSageServerServer(s grpc.ServiceRegistrar, srv DataSageServerServer) {
	s.RegisterService(&DataSageServer_ServiceDesc, srv)
}

func _DataSageServer_LogSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Log)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSageServerServer).LogSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DataSageServer/LogSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSageServerServer).LogSend(ctx, req.(*Log))
	}
	return interceptor(ctx, in, info, handler)
}

// DataSageServer_ServiceDesc is the grpc.ServiceDesc for DataSageServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataSageServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DataSageServer",
	HandlerType: (*DataSageServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogSend",
			Handler:    _DataSageServer_LogSend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datasage.proto",
}
